### PR TITLE
fix: xpc error

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by stehessel** [comment]
FYI there are currently problems with nix and Intel Darwin. Sadly many Darwin contributors have the new arm chips, so not much love for Intel Darwin :(. So it may be that the intel macOS SDK in nix is too old for some deps. See also https://github.com/NixOS/nixpkgs/issues/101229.

**Comment by stehessel** [comment]
What is the xpc error that this is fixing?

**Comment by janisz** [comment]
> What is the xpc error that this is fixing?

```
# github.com/google/certificate-transparency-go/x509
In file included from ../../../go/pkg/mod/github.com/google/certificate-transparency-go@v1.1.6/x509/root_cgo_darwin.go:[18](https://github.com/stackrox/stackrox/actions/runs/6867691700/job/18676599451#step:6:19):
In file included from /nix/store/4ap5801d9ijdl3v89hsxxz18y5724qly-apple-framework-Security-11.0.0/Library/Frameworks/Security.framework/Headers/Security.h:87:
/nix/store/4ap5801d9ijdl3v89hsxxz18y5724qly-apple-framework-Security-11.0.0/Library/Frameworks/Security.framework/Headers/SecCode.h:35:10: fatal error: 'xpc/xpc.h' file not found
#include <xpc/xpc.h>
         ^~~~~~~~~~~
1 error generated.
```
https://github.com/stackrox/stackrox/actions/runs/6867691700/job/18676599451#step:6:22

**Comment by janisz** [comment]
After adding SDK
```
# github.com/stackrox/rox/central/activecomponent/updater.test
/nix/store/anpa648cir6s5zppxr0hlj20ryxxzbxv-go-1.20.11/share/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "_SecTrustEvaluateWithError", referenced from:
      _crypto/x509/internal/macos.x509_SecTrustEvaluateWithError_trampoline.abi0 in go.o
  "_utimensat", referenced from:
      _syscall.libc_utimensat_trampoline.abi0 in go.o
ld: symbol(s) not found for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```
https://github.com/stackrox/stackrox/actions/runs/6867691700/job/18676599451#step:6:22

**Pull request closed without merging**
